name: win_assist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.2.4
  percent_indicator: ^4.2.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.4
  go_router: ^12.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  logger: ^2.0.2+1
  xterm: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
